### ISSUE TITLE
non geographic data

### ISSUE THREAD

**Issue by cornhundred** [tilezen/mapbox-vector-tile#109]
Is it possible to generate MVT tiles from non-geographic data - e.g. X and Y coordinates on a 2D plane?

**Comment by nvkelso** [comment]
You can certainly "fake" your data into web mercator projection, but it would involve some scaling tricks. You might want to try Carto or MapTiler as they support multiple projections with GUI tools.

**Comment by cornhundred** [comment]
Thanks @nvkelso I'll look into that
