### ISSUE TITLE
Why mapbox-vector-tile doesn't support list value in property?

### ISSUE THREAD

**Issue by timewalker08** [tilezen/mapbox-vector-tile#135]
I read the code, and following function determine the type of value supported.
`def _can_handle_val(v):
        return isinstance(v, (str, bool, int, float))`
I have a list in my property, I find it is lost in the resulf of encode. Why list value is not supported?

**Comment by rmarianski** [comment]
not supported directly by the [spec](https://github.com/mapbox/vector-tile-spec/blob/5330dfc6ba2d5f8c8278c2c4f56fff2c7dee1dbd/2.1/vector_tile.proto#L17-L28). A typical work around is to encode it as a string, eg comma separated, or as json.

**Comment by timewalker08** [comment]
Thank you for clarification
