### ISSUE TITLE
 DLL load failed while importing _pyclipper

### ISSUE THREAD

**Issue by Tomas-mo** [tilezen/mapbox-vector-tile#137]
Dear Robert,
 
Thank you for a excellent package. I have been using it for a couple of months on one computer, where it has been working perfectly.

Now I have tried to install it on another computer with the same python enviorment. Python 3.10, Pycharm 2021.3.2.  The installation of mapbox-vector-tiles seems to work. But when running a simple test code ( the first part of your example), I get the following error message :

Traceback (most recent call last):
  File "C:\Users\Offlinekonto\PycharmProjects\test_proj\mvt_test.py", line 1, in <module>
    import mapbox_vector_tile
  File "C:\Users\Offlinekonto\PycharmProjects\test_proj\venv\lib\site-packages\mapbox_vector_tile\__init__.py", line 3, in <module>
    from mapbox_vector_tile import decoder, encoder
  File "C:\Users\Offlinekonto\PycharmProjects\test_proj\venv\lib\site-packages\mapbox_vector_tile\encoder.py", line 13, in <module>
    from mapbox_vector_tile.polygon import make_it_valid
  File "C:\Users\Offlinekonto\PycharmProjects\test_proj\venv\lib\site-packages\mapbox_vector_tile\polygon.py", line 1, in <module>
    import pyclipper
  File "C:\Users\Offlinekonto\PycharmProjects\test_proj\venv\lib\site-packages\pyclipper\__init__.py", line 1, in <module>
    from ._pyclipper import *
ImportError: DLL load failed while importing _pyclipper: Det går inte att hitta den angivna modulen.

The last part in swedish translate "Can not find the named module"

I have notice a discrepancy between the installation on the computer where the package is working, in that installation I find pyclipper among the Binary Skeletons but not in the installation on the new computer.

Do you have any suggestions how I might  solve this issue.

Best Regards
Tomas

**Comment by rmarianski** [comment]
it looks like pyclipper is not installed, or at least not picked up properly when running the tests. Try re-installing the dependencies.

```bash
poetry install
poetry run pytest
```

But if that's not how you're managing dependencies, try re-installing using that method, or at least re-installing pyclipper.

I'm not familiar with windows, so I'm afraid I can't offer more specific help.

**Comment by Tomas-mo** [comment]
Hi, Thanks för your answer. I managed to install every thing needed using conda now it works fine.Regards TomasSkickat från min iPhone7 dec. 2024 kl. 17:04 skrev Robert Marianski ***@***.***>:﻿
it looks like pyclipper is not installed, or at least not picked up properly when running the tests. Try re-installing the dependencies.
poetry install
poetry run pytest
But if that's not how you're managing dependencies, try re-installing using that method, or at least re-installing pyclipper.
I'm not familiar with windows, so I'm afraid I can't offer more specific help.
