### ISSUE TITLE
Handle invalid geometries

### ISSUE THREAD

**Issue by rmarianski** [tilezen/mapbox-vector-tile#45]
After quantizing and encoding mvt tiles, we can end up in situations where we generate invalid geometries. The encoder should allow for the flexibility to handle these in different ways, eg drop invalid geometries, try to correct the geometry and try again, raise an exception, etc. Offering a callback might be a general way to approach the implementation.

**Comment by rmarianski** [comment]
Related to https://github.com/mapzen/mapbox-vector-tile/issues/42

**Comment by nvkelso** [comment]
@rmarianski Anything more to test with this one before taking it to prod?

**Comment by rmarianski** [comment]
Good to go.
