### ISSUE TITLE
A Puzzle of Winding Order

### ISSUE THREAD

**Issue by fosskers** [tilezen/mapbox-vector-tile#57]
Hi there. I'm currently putting together a VectorTile (v2) codec, much like this library here but in another language. I found this while looking for an independant tool to verify my schema and the `protobuf` library I'm using. I've been experimenting with `mapbox-vector-tile` almost all day now, and so far I've managed the following:

* [x] Encode a hand-written instance of my schema type, and decode it with `mapbox-vector-tile`
* [x] Decode a tile of a single `Point` written by `mapbox-vector-tile` into my schema type
* [x] Decode a tile of a single `LineString` written by `mapbox-vector-tile` into my schema type

Initially I was having problems with how `geometries` were being encoded by `mapbox-vector-tile`, until I discovered `y_coord_down`. The next logical step was, of course, to attempt a `Polygon`. So, I encoded and wrote the following from python:

```python
 vt = {
     "name": "OnePolygon",
     "features": [
         {
             "geometry":"POLYGON ((2 2, 5 4, 2 6, 2 2))",
             "properties": {}
         }
     ]
 }
```
while following the example from the README. Now, the points `(2,2) -> (5,4) -> (2,6) -> (2,2)` are in clockwise winding order (and also produce a positive area from the [surveyor's formula](https://en.wikipedia.org/wiki/Shoelace_formula)) *if* we're working with y-down coordinates. So:

```python
encoded = mapbox_vector_tile.encode([vt], y_coord_down=True)
```

I expected this `Polygon` to be encoded as: 
```python
[ 
  9 4 4   # MoveTo(+2,+2) 
  18 6 4 5 4 # LineTo(+3,+2), LineTo(-3,+2)
  15  # ClosePath
]
```
but instead found it to be:
```python
[
  9 4 4 # MoveTo(+2,+2) 
  18 0 8 6 3 # LineTo(+0,+4), LineTo(+3,-2)
  15 # ClosePath
]
``` 
which in fact represents: `(2,2) -> (2,6) -> (5,4) -> (2,2)`, the opposite winding of before. Despite defining the `Polygon` in clockwise order (in y-down space) as `POLYGON ((2 2, 5 4, 2 6, 2 2))`, the points were rearranged to form the counter-clockwise order. In v2 of the spec, this would be considered an interior ring, as it has negative area in y-down space.

How does this library handle winding order?

**Comment by nvkelso** [comment]
@flippmoke Can you comment on this, please? I've gotten pretty confused :\

**Comment by fosskers** [comment]
Any thoughts?

**Comment by nvkelso** [comment]
Documentation: 

- Spec: https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4356-example-multi-polygon
- With pictures: https://www.mapbox.com/vector-tiles/specification/#winding-order

Could be we're doing it wrong!

**Comment by zerebubuth** [comment]
Hi @fosskers. I think we might have fixed the bug in #59 and we've released a new version, 0.4.0, of the PyPI package. Please could you test that and see if there's still an issue?

**Comment by fosskers** [comment]
Works like a charm! Testing against my [Haskell codec](https://github.com/fosskers/vectortiles) confirms the fix. I have some benchmarks comparing the two, but oddly enough PyPy 5.3 fails to encode anything, instead outputting many lines of `ParseException: Unknown WKB type 79`. The number isn't always 79, though.

**Comment by nvkelso** [comment]
Great to hear, thanks!
