### ISSUE TITLE
Where to explain performance tips ?

### ISSUE THREAD

**Issue by lexman** [tilezen/mapbox-vector-tile#80]
Hello,
in our struggle for performance we've found a cheap optimization : using the C++ version of protobuf instead of the python one. It's all decribed [here](https://github.com/google/protobuf/tree/v2.6.1/python) : just set two environment variables before you run your program (PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp and ROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2) and you get speedup for free (25 % in our usecase without quantization nor winding order). You might ask why version 2.6.1 ? Because we're on debian 8, and we use the same python package version than the apt python-protobuf package.

So, now my question is : is there somewhere in the project where we can leave track of this tip ?

**Comment by rmarianski** [comment]
Nice find! :zap: 

I think the [README.md](https://github.com/tilezen/mapbox-vector-tile/blob/master/README.md) file is the appropriate place to document this. Mind submitting a pr to add a note in there?

**Comment by lexman** [comment]
I'll do that, likely on thuesday...

**Comment by lexman** [comment]
I've made a PR : https://github.com/tilezen/mapbox-vector-tile/pull/81

**Comment by nvkelso** [comment]
This was merged, closing.
